config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include('kun.urls')),
    path('admin/', admin.site.urls),
    path('accaunts/', include('django.contrib.auth.urls')),
    path('accaunts/', include('accaunts.urls'))
]

function-app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('admin/', admin.site.urls),
    path('contact/', include('contact.urls'))
]

function-app/contact/urls.py
from django.urls import path
from .views import (contact_list_page,
                    details,
                    create_page,
                    create,
                    delete,
                    delete_page,
                    add_page,
                    add)
app_name = 'contact'
urlpatterns = [
    path('list/', contact_list_page, name='contact'),
    path('add_page/<int:pk>/', add_page, name='add_page'),
    path('add/<int:pk>/', add, name='add'),
    path('details/<int:pk>/', details, name='detail'),
    path('create_page/', create_page, name='create_page'),
    path('create/', create, name='create'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('delete_page/<int:pk>/', delete_page, name='delete_page'),

]

qalampir/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('qalampir.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls)
]

# if settings.DEBUG:
#     import debug_toolbar
#
#     urlpatterns = [
#                       path('__debug__/', include(debug_toolbar.urls)),
#                   ] + urlpatterns
#     urlpatterns += w(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sss/daryo/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include


def home(request):
    return redirect(to="yangiliklar:news")


urlpatterns = [
    path('', home, name='home'),
    path('news/', include('yangiliklar.urls')),
    path('admin/', admin.site.urls),
]

function-app/contact/models.py
from django.db import models
from .contants import Phonetype


# Create your models here.


class Contact(models.Model):
    name = models.CharField(max_length=100)

    # created_by = models.

    def __str__(self):
        return self.name


class Phone(models.Model):
    number = models.CharField(max_length=13)
    contacts = models.ForeignKey('Contact', on_delete=models.CASCADE)
    type = models.CharField(max_length=100, choices=Phonetype.choises())

    def __str__(self):
        return self.number

function-app/contact/views.py
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage
from django.shortcuts import render
from django.shortcuts import render, redirect
# Create your views here.
from django.views.decorators.http import require_POST, require_safe
from .models import Contact, Phone, Phonetype


@require_safe
def contact_list_page(request):
    page = request.GET.get('page', 1)
    content = Contact.objects.all()
    paginator = Paginator(content, 2)
    try:
        content = paginator.page(page)
    except EmptyPage:
        content = paginator.page(1)
    return render(request, 'list.html', {'contacts': content})




def home(request):
    return render(request, 'index.html', {})


@require_safe
def details(request, pk):
    contact = Contact.objects.get(pk=pk)
    return render(request, 'details.html', {'contact': contact})


@require_safe
def create_page(request):
    choises = Phonetype.proccess()
    return render(request, "create.html", {'choises': choises})


@require_POST
def create(request):
    name = request.POST['name']
    number = request.POST['number']
    _type = request.POST['type']
    contact = Contact(name=name)
    contact.save()
    phone = Phone(number=number, type=_type, contacts=contact)
    phone.save()
    messages.info(request, 'Successfully created', extra_tags='success')
    return redirect('contact:contact')


def delete(request, pk):
    contact = Contact.objects.get(pk=pk)
    contact.delete()
    return redirect('contact:contact')


def delete_page(request, pk):
    contact = Contact.objects.get(pk=pk)
    return render(request, 'delete.html', {'contact': contact})


def add_page(request, pk):
    choise = Phonetype.proccess()
    contact = Contact.objects.get(pk=pk)
    return render(request, 'add_page.html', {'choises': choise, 'contact': contact})


def add(request, pk):
    contact = Contact.objects.get(pk=pk)
    number = request.POST['number']
    _type = request.POST['type']
    phone = Phone(number=number, type=_type, contacts=contact)
    phone.save()
    return redirect('contact:detail', pk=pk)

function-app/templates/add_page.html
{% extends 'base.html' %}

{% block title %}
    Create contact
{% endblock %}


{% block conten %}
    <div class="row">
        <div class="offset-2 mt-3 col-8">
            <form action="{% url 'contact:add' contact.id %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}


                <div class="mb-3">
                    <label for="number">Contact number</label>
                    <input type="number" class="form-control" name='number' id="number"
                           placeholder="+998908085480">
                </div>
                <select class="form-select form-control " name="type">
                    {% for choise in choises %}
                        {% if forloop.counter == 1 %}
                            <option selected class="form-control" value="{{ choise.name }}">{{ choise.value }}</option>
                        {% else %}
                            <option selected value="{{ choise.name }}">{{ choise.value }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
                <input type="submit" value="save" class="btn btn-success mt-2 ">
                <a href="{% url 'contact:detail' contact.id %}" class="mt-2 btn btn-warning">Back</a>
            </form>


        </div>
    </div>
{% endblock %}

function-app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'contact:contact' %}">Contacts</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>
<section>
    <div class="row">
        <div class="offset-2 col-8">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
</section>
<main>
    {% block conten %}

    {% endblock %}
</main>


<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</body>
</html>

function-app/templates/create.html
{% extends 'base.html' %}

{% block title %}
    Create contact
{% endblock %}


{% block conten %}
    <div class="row">
        <div class="offset-2 mt-3 col-8">
            <form action="{% url 'contact:create' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="form-group">
                    <label for="name">Contact name</label>
                    <input type="text" class="form-control" name='name' id="name"
                           placeholder="Sunnat">
                </div>

                <div class="mb-3">
                    <label for="number">Contact number</label>
                    <input type="number" class="form-control" name='number' id="number"
                           placeholder="+998908085480">
                </div>
                <select class="form-select form-control " name="type">
                    {% for choise in choises %}
                        {% if forloop.counter == 1 %}
                            <option selected class="form-control" value="{{ choise.name }}">{{ choise.value }}</option>
                        {% else %}
                            <option selected value="{{ choise.name }}">{{ choise.value }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
                <input type="submit" value="save" class="btn btn-success mt-2 ">
                <a href="{% url 'contact:contact' %}" class="mt-2 btn btn-warning">Back</a>
            </form>


        </div>
    </div>
{% endblock %}

function-app/templates/delete.html
{% extends 'base.html' %}

{% block title %}
    Create contact
{% endblock %}


{% block conten %}
    <div class="row">
        <div class="offset-2 mt-3 col-8">
            <form action="{% url 'contact:delete' contact.id %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="alert alert-danger">
                    Wanna delete <strong>{{ contact.name }}</strong>
                </div>
                <input type="submit" value="delete" class="btn btn-success mt-2 ">
                <a href="{% url 'contact:contact' %}" class="mt-2 btn btn-warning">Back</a>
            </form>
        </div>
    </div>
{% endblock %}

function-app/templates/details.html
{% extends 'base.html' %}

{% block title %}
    Contact list
{% endblock %}


{% block conten %}
    <div class="row">
        <div class="offset-4 mt-3 col-3">
            <div class="card text-center">
                <a href="{% url 'contact:detail' pk=contact.id %}" class="h1">{{ contact.name }}</a>
                {% if contact.phone_set.all %}
                    <ul class="list-group">
                        {% for phone in contact.phone_set.all %}
                            <li class="list-group-item"><strong>{{ phone.type }}</strong>{{ phone.number }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
            <a href="{% url 'contact:contact' %}" class="btn mt-2 btn-warning">Back</a>
            <a href="{% url 'contact:add_page' contact.id %}" class="btn mx-4 mt-2 btn-success">Add Number</a>
            <a href="{% url 'contact:delete_page' contact.id %}" class="btn mt-2 btn-danger">Delete</a>
        </div>
    </div>
{% endblock %}

function-app/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Contact list
{% endblock %}


{% block conten %}
    <div class="row">
        <div class="offset-2 col-8">
           <h2>Home Page</h2>
        </div>
    </div>
{% endblock %}

function-app/templates/list.html
{% extends 'base.html' %}

{% block title %}
    Contact list
{% endblock %}


{% block conten %}
    <div class="row mx-3">

        {% for contact in contacts %}
            <div class="mt-4 col-3">
                <div class="card text-center" style="width: 300px">
                    <a href="{% url 'contact:detail' pk=contact.id %}" class="h1">{{ contact.name }}</a>
                    {% if contact.phone_set.all %}
                        <ul class="list-group">
                            {% for phone in contact.phone_set.all %}
                                <li class="list-group-item"><strong
                                        class="mr-1"> {{ phone.type }}-</strong>{{ phone.number }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>{% endfor %}


    </div><a href="{% url 'contact:create_page' %}" class="btn ml-4 mt-5 btn-success">Create contact</a>
    {% if contacts.paginator.page_range %}
        <nav aria-label="Page navigation example">


            <ul class="pagination">
                {% for paginato in contacts.paginator.page_range %}
                    <li class="page-item"><a class="page-link" href="?page={{ paginato }}">{{ paginato }}</a></li>
                {% endfor %}

            </ul>

        </nav>
    {% endif %}
{% endblock %}