config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include('kun.urls')),
    path('admin/', admin.site.urls),
    path('accaunts/', include('django.contrib.auth.urls')),
    path('accaunts/', include('accaunts.urls'))
]

qalampir/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('qalampir.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls)
]

# if settings.DEBUG:
#     import debug_toolbar
#
#     urlpatterns = [
#                       path('__debug__/', include(debug_toolbar.urls)),
#                   ] + urlpatterns
#     urlpatterns += w(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sss/daryo/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include


def home(request):
    return redirect(to="yangiliklar:news")


urlpatterns = [
    path('', home, name='home'),
    path('news/', include('yangiliklar.urls')),
    path('admin/', admin.site.urls),
]

sss/yangiliklar/urls.py
from django.urls import path
from yangiliklar.views import (
    post_list_page,
    post_create,
    post_create_page,
    post_detail_page)

app_name = 'yangiliklar'

urlpatterns = [
    path('', post_list_page, name='news'),
    path('post_create/', post_create, name='post_create'),
    path('post_create_page/', post_create_page, name='post_create_page'),
    path('post_detail_page/<int:post_id>', post_detail_page, name='post_detail_page'),
]

sss/yangiliklar/models.py
from django.db import models
from django.contrib.admin.decorators import register


# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200)
    overview = models.TextField()
    body = models.TextField()
    posted_by = models.IntegerField(default=-1, null=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "News"

    def __str__(self):
        return self.title


class Like(models.Model):
    is_like = models.IntegerField(default=1, null=False)
    liked_by = models.IntegerField(default=-1, null=False)
    post = models.ForeignKey(Post, on_delete=models.DO_NOTHING)

    class Meta:
        db_table = "likes"

    def __str__(self):
        return str(self.post.id)


class Comment(models.Model):
    comment = models.CharField(max_length=270)
    commented_by = models.IntegerField(default=-1, null=False)
    post = models.ForeignKey(Post, on_delete=models.DO_NOTHING)

    class Meta:
        db_table = "comments"

    def __str__(self):
        return self.comment

sss/yangiliklar/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST, require_GET, require_http_methods

# Create your views here.
from daryo.utils import *
from yangiliklar.models import Post


@require_GET
def post_list_page(request):
    posts = Post.objects.all()
    content = {'posts': posts}
    return render(request=request, template_name="news.html", context=content)


@require_POST
def post_create(request):
    title = request.POST['title']
    overview = request.POST['overview']
    body = request.POST['body']
    post = Post(title=title, overview=overview, body=body)
    post.save()
    return redirect("yangiliklar:news")


@require_GET
def post_create_page(request):
    return render(request, "create_post.html")


@require_GET
def post_detail_page(request, post_id):
    post = Post.objects.get(pk=post_id)
    return render(request, 'detaill.html', {'post': post})

sss/yangiliklar/templates/create_post.html
{% extends 'layout.html' %}

{% block title %}
    News
{% endblock %}


{% block content %}
    <form action="{% url 'yangiliklar:post_create' %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="title" class="form-label">Title</label>
            <input type="text" class="form-control" name="title" id="title">
        </div>

        <div class="mb-3">
            <label for="overview" class="form-label">Overview</label>
            <textarea class="form-control" name="overview" id="overview" rows="3"></textarea>
        </div>

        <div class="mb-3">
            <label for="body" class="form-label">Body</label>
            <textarea class="form-control" name="body" id="body" rows="6"></textarea>
        </div>
        <input type="submit" class="btn btn-success" value="save"/>

    </form>
{% endblock %}

sss/yangiliklar/templates/detail.html
{% extends 'layout.html' %}

{% block title %}
    News
{% endblock %}


{% block content %}
    {% if post %}
        <div class="border border-1 m-2">
            <h2>{{ post.title | safe }}</h2>
            <p class="pl-2">{{ post.overview | safe }}</p>
            <p class="pl-2">{{ post.body | safe }}</p>
            <p class="pl-2">Posted At : {{ post.created_at |date }} {{ post.created_at |time }}</p>
            <p class="pl-2">Author {{ post.posted_by }}</p>
        </div>
        <hr/>
        <a href="{% url 'yangiliklar:news' %}">Back</a>
    {% else %}
        <div class="alert alert-warning">Posts not available</div>
    {% endif %}
{% endblock %}

sss/yangiliklar/templates/news.html
{% extends 'layout.html' %}

{% block title %}
    News
{% endblock %}


{% block content %}
    {% if posts %}
        {% for post in posts %}
            <div class="border border-1 m-2">
                <h2><a href="{% url 'yangiliklar:post_detail_page' post.id %}" class="btn">{{ post.title | safe }}</a>
                </h2>
                <p class="pl-2">{{ post.overview | safe }}</p>
            </div>
        {% endfor %}
        <hr/>
        <a href="{% url 'yangiliklar:post_create_page' %}">Create Post</a>
    {% else %}
        <div class="alert alert-warning">Posts not available</div>
    {% endif %}
{% endblock %}